### ISSUE TITLE
Need to help in setup

### ISSUE THREAD

**Issue by karthi3219** [anandanand84/technicalindicators#47] opened 2017-06-18 11:35 UTC
Hi, I want to setup the project. I have downloaded the project. Extracted the zip to the folder 'technicalindicators-master'. I ran the  'npm install --save technicalindicators'. It installed the node_modules folder in the root directory. After this I have written the below simple script to check the Bearish Engulfing Pattern. 
```
var BearishEngulfingPattern = require('technicalindicators').BearishEngulfingPattern;
var twoDayBearishInput = {
  open: [21.44,27.89],
  high: [25.10,30.87],
  close: [23.25,15.36],
  low: [20.82,14.93],
}
var result      = BearishEngulfingPattern.hasPattern(twoDayBearishInput);
console.log( 'Is BearishEngulfingPattern? :' +result); 
```
But I am getting below error.
```
TypeError: Cannot read property 'hasPattern' of undefined
    at Object.<anonymous> (/home/lk/Downloads/technicalindicators-master/node_c975eebf38a1f.tmp:8:42)
    at Module._compile (module.js:570:32)
```
I am very new to the nodejs world. Could you please someone help me how to resolve this? I debug and found that the `require('technicalindicators').BearishEngulfingPattern` is returning unidentified.

**Comment by anandanand84** [comment] 2017-06-18 14:44
This issue is a duplicate of https://github.com/anandanand84/technicalindicators/issues/38

Below are the steps anyways.

Actually, you dont have to extract the zip, Just go to a new folder and follow the steps

1.  `npm init` this creates a new nodejs project.
2. `npm install --save technicalindicators` this installs and saves the technical indicators dependency.

3. Create a new file(index.js) and use below code.

```
var bearishengulfingpattern =require('technicalindicators'). bearishengulfingpattern;

var twoDayBearishInput = {
  open: [21.44,27.89],
  high: [25.10,30.87],
  close: [23.25,15.36],
  low: [20.82,14.93],
}

var result      = bearishengulfingpattern(twoDayBearishInput);
console.log('Is Bearish Engulfing Pattern? :' +result);

```

4.  run `node index.js`
with the latest code you dont have to use has pattern any more. Actually in runkit examples it uses old version, so it working, I'll update the runkit examples. Thankyou. See below the list of export names

https://github.com/anandanand84/technicalindicators/blob/master/src/index.ts

**Closed** 2017-06-19 12:54 UTC
