### ISSUE TITLE
TypeError: Cannot read property 'toFixed' of undefined

### ISSUE THREAD

**Issue by zachnoren** [anandanand84/technicalindicators#41] opened 2017-04-22 22:50 UTC
When using the MACD function getting this error here is the stack trace

`TypeError: Cannot read property 'toFixed' of undefined
    at format (node_modules/technicalindicators/lib/Utils/NumberFormatter.js:4:24)
    at node_modules/technicalindicators/lib/moving_averages/MACD.js:52:27
    at next (native)
    at MACD.input.values.forEach (node_modules/technicalindicators/lib/moving_averages/MACD.js:62:41)
    at Array.forEach (native)
    at MACD (node_modules/technicalindicators/lib/moving_averages/MACD.js:61:22)
    at Function.macd [as calculate] (node_modules/technicalindicators/lib/moving_averages/MACD.js:78:18)`

portions of the file path were removed, verified the data is coming in in the right format

**Comment by anandanand84** [comment] 2017-04-23 00:00
can you give me the data you used?

**Comment by anandanand84** [comment] 2017-06-19 12:55
@zachnoren Are you still facing this issue?

**Comment by leomar-developer** [comment] 2017-07-23 02:03
I'm  having this issue too, the data is just too large to be posted here and it comes from a JSON API, I would need to save the result to a text file in order to attach it here, just as a hint at least in my case it seems to be related with datasets with very small values like 0.00000071 and such as I only get this error when using datasets with such very small values.

**Comment by anandanand84** [comment] 2017-07-23 03:31
@leomar-developer what version are you using?

**Comment by leomar-developer** [comment] 2017-07-23 03:39
I'm using 1.0.5 @anandanand84

**Comment by anandanand84** [comment] 2017-07-23 04:06
@leomar-developer Thanks I'll take a look.

**Comment by anandanand84** [comment] 2017-07-26 15:28
@leomar-developer can you check if you still face this issue with 1.0.8 I believe it is fixed. If it is still there can you send the data you are using it is hard to fix without reproducing

**Comment by anandanand84** [comment] 2017-07-26 21:10
This should be fixed. Reopen otherwise

**Closed by anandanand84** 2017-07-26 21:10 UTC

**Comment by leomar-developer** [comment] 2017-07-30 20:09
Hi @anandanand84 sorry for being late on getting back to this, I could not test with 1.0.8 as I have been busy with other things on the project I didn't want to change versions just yet, seems the error in my case was on my side as I was already doing a `n.Tofixed` on each data item before sending the whole dataset to the MACD indicator function, after I added a `parseFloat` to my data it started to work just fine even with small numbers, however I do noticed a problem with the Rate of Change indicator as it seems that when you use it with transitions from negative to positive numbers the result is negative, for example:

`indicators.ROC.calculate({ period: 1, values [-4, 2]})`

Gives as result `[-150]`, shouldn't it be 150 (positive) as you are going from a lower value to a higher one? or is the ROC indicator not suitable for this kind of use? (measuring change from negative to positive)

**Comment by leomar-developer** [comment] 2017-07-30 20:30
I think you just need to use an ABS for the denominator here:

`roc = ((tick - pastPeriods.lastShift) / (pastPeriods.lastShift)) * 100;`

so it becomes:

`roc = ((tick - pastPeriods.lastShift) / (Math.abs(pastPeriods.lastShift))) * 100;`

I'm not a math guy so I ignore if the ROC indicator would not work properly by doing that or if this is really a fix for a bug on its calculation.
